/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qg3w' at '12/30/15 11:37 AM' with Gradle 2.10
 *
 * @author qg3w, @date 12/30/15 11:37 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
